
login = {
    "seed_main_sensor": "CSFFTG9AWDQVEJERDCDOUBVW9EHEBUZCYUAUTSQRLWXJLALAMAVEOCIQWLDWEPMJKWLLLVKOO9UDIHAZB",
    "target_addres_monitor": "VEU9UBWBCLWFNQUROTTHGGSRHLTLWCRJVDCYSARBVLFODE9UBYWDHZEOYAS9O9SYAMDRKSFXRHIVBBDMC"
}