

login = {
    'seed_main_sensor' : 'ERXDLN9EHDNXUIRPDHLHLBAIZMKYFXCTBXSRBTORWKSWGXBENPVADTMXCHLMVNXLAHWESARITEIPWDBKH',
    'target_addres_monitor' : 'PDQXZKHGQPFAAOWFYSZAGAGTUHKUIXUANO9NFOHRPIJC9DPOEHHIOJXHLVJFKQHXWMCPNSFFXVY9IO9AW'
}


# login = {
#     'seed_main_sensor' : 'TIVZZNKBDGCOKNCADJZPMYBDAFNWXIY9KY9MXAMGFRSFNNPMEFWEXYYDVHIAYJXPRZIWS9DFAEXLLV9DI',
#     'target_addres_monitor' : 'KUFLDHABKEGGVZMVNVHRUMFWFK9JOIF9JTRKNMQ9HRRNCSORJWTIKFNMAJLOSUGJJWZRVKABNNTVHMSJC'
# }