



login = {
    'seed_main_monitor' : 'DXJPWCCKD9JDSLHSYIYNLAPWXNIQCRAPDVGMHCWBRR9VFOUBLQVRPPEZNPBLWVAZLZWCOYGYUNBHRSBHJ',
    'target_address' : 'PDQXZKHGQPFAAOWFYSZAGAGTUHKUIXUANO9NFOHRPIJC9DPOEHHIOJXHLVJFKQHXWMCPNSFFXVY9IO9AW'
}


# login = {
#     'seed_main_monitor' : 'NXADKYQJTXOUFZPBZIRZ99DERHU9DQBUBTJNDLSOVFPIXVUFLIZHQH9UJATUCHNCIZRYGKSDSCTGBKKWX',
#     'target_address' : 'KUFLDHABKEGGVZMVNVHRUMFWFK9JOIF9JTRKNMQ9HRRNCSORJWTIKFNMAJLOSUGJJWZRVKABNNTVHMSJC'
# }
