

login = {
    "seed_main_monitor": "JQAR9IWODHMSYWQOAWDZ9KXFFKDODONYXFZAXGCDLEXMPQKFGUHPIP9QAHFXORFORGFFRTTQG9YFNFXNH",
    "target_address": "VEU9UBWBCLWFNQUROTTHGGSRHLTLWCRJVDCYSARBVLFODE9UBYWDHZEOYAS9O9SYAMDRKSFXRHIVBBDMC"
}